Target-template alignment
>P1;SETD8_HUMAN_D0
sequence:SETD8_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
SRKSKAELQSEERKRIDELIESGKEEGMKIDLIDGKGRGVIATKQFSRGDFVVEYHGDLIEITDAKKREALYAQDPSTGCYMYYFQYLSKTYCVDATRETNRLGRLINHSKCGNCQTKLHDIDGVPHLILIASRDIAAGEELLYDYGDRSKASIEAHPWLKH*
>P1;SETD8_HUMAN_4IJ8_B
structureX:SETD8_HUMAN_4IJ8_B:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
------------RKRIDELIESGKEEGMKIDLIDGKGRGVIATKQFSRGDFVVEYHGDLIEITDAKKREALYAQDPSTGCYMYYFQYLSKTYCVDATRETNRLGRLINHSK-GNCQTKLHDIDGVPHLILIASRDIAAGEELLYDYGDRSKASIEAHPWLKH*
