Target-template alignment
>P1;KMT5A_HUMAN_D0
sequence:KMT5A_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
SRKSKAELQSEERKRIDELIESGKEEGMKIDLIDGKGRGVIATKQFSRGDFVVEYHGDLIEITDAKKREALYAQDPSTGCYMYYFQYLSKTYCVDATRETNRLGRLINHSKCGNCQTKLHDIDGVPHLILIASRDIAAGEELLYDYGDRSKASIEAHPWLKH*
>P1;KMT5A_HUMAN_TDIZ_B
structureX:KMT5A_HUMAN_TDIZ_B:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
--------------RIDELIESGKEEGMKIDLIDGKGRGVIATKQFSRGDFVVEYHGDLIEITDAKKREALYAQDPSTGCYMYYFQYLSKTYCVDATRETNRLGRLINHSKSGNCQTKLHDIDGVPHLILIASRDIAAGEELLYDYGDR-------------*
